const adminMain = document.querySelector("#adminMain");
const toast = document.querySelector(".admin-toast");
const sidebar = document.querySelector("#sidebar");
const sidebarToggle = document.querySelector(".sidebar-toggle");
const rolePreview = document.querySelector("#rolePreview");
let toastTimer;

const adminField = (label, value = "", type = "text", helper = "") => `<div class="admin-field"><label>${label}</label>${type === "textarea" ? `<textarea>${value}</textarea>` : type === "select" ? `<select>${value}</select>` : `<input type="${type}" value="${value}" />`}${helper ? `<p class="helper">${helper}</p>` : ""}</div>`;
const pageHead = (title, text, actions = "") => `<div class="page-head"><div><h1>${title}</h1><p>${text}</p></div>${actions ? `<div class="head-actions">${actions}</div>` : ""}</div>`;
const saveButton = `<button class="admin-btn admin-btn--primary static-save" type="button">Save changes</button>`;

function dashboard() {
  return `<div class="admin-page">${pageHead("Good afternoon, Adil.", "Here’s what needs attention for Rijswijk 2026.", `<a class="admin-btn admin-btn--outline" href="index.html?page=home" target="_blank">Preview website ↗</a>`)}
  <div class="metric-grid"><article class="metric"><div class="metric-top"><span class="metric-icon">◎</span><small>+3 this week</small></div><b>28</b><span>Active exhibitors</span></article><article class="metric"><div class="metric-top"><span class="metric-icon">✉</span><small>5 new</small></div><b>42</b><span>Open requests</span></article><article class="metric"><div class="metric-top"><span class="metric-icon">⇄</span><small>2 awaiting reply</small></div><b>17</b><span>Fair Match requests</span></article><article class="metric"><div class="metric-top"><span class="metric-icon">文</span><small>Arabic RTL active</small></div><b>78%</b><span>Translation completeness</span></article></div>
  <div class="dash-grid"><section class="panel"><div class="panel-head"><h2>Recent activity</h2><a href="admin.html?page=requests">View requests →</a></div><div class="panel-body"><ul class="activity"><li><span>✉</span><p><b>New exhibitor participation request</b><small>Alara Clinic · Stand 2 interest</small></p><time>12 min</time></li><li><span>⇄</span><p><b>Fair Match request updated</b><small>Nova Medical Group · alternative time proposed</small></p><time>36 min</time></li><li><span>◎</span><p><b>Exhibitor published</b><small>Lumen Skin Science is now visible</small></p><time>2 hrs</time></li><li><span>文</span><p><b>Turkish content edited</b><small>Homepage hero and visitor section</small></p><time>Yesterday</time></li></ul></div></section><section class="panel"><div class="panel-head"><h2>Launch readiness</h2><a href="admin.html?page=launch">Open checklist →</a></div><div class="readiness"><div class="progress-ring"></div><p>Core content is in good shape.<br />Final links and approvals remain.</p><div class="status-list" style="width:100%"><div class="status-item"><span>Public pages</span><b class="status status--success">Ready</b></div><div class="status-item"><span>Translations</span><b class="status status--warning">Review</b></div><div class="status-item"><span>Ticket link</span><b class="status status--danger">Missing</b></div><div class="status-item"><span>Legal copy</span><b class="status status--warning">Approval</b></div></div></div></section></div></div>`;
}

function eventPage() {
  return `<div class="admin-page">${pageHead("Event management", "Edit the predefined details and publication state for Rijswijk 2026.", `<button class="admin-btn admin-btn--outline" type="button">Preview</button>${saveButton}`)}
  <div class="admin-grid"><section class="form-panel"><h2>Core event information</h2><div class="form-row">${adminField("Event name","Health & Beauty Expo Rijswijk 2026")}${adminField("Publication status","<option>Published</option><option>Draft</option>","select")}</div><div class="form-row">${adminField("Start date","2026-10-24","date")}${adminField("End date","2026-10-25","date")}</div><div class="form-row">${adminField("Opening time","10:00","time")}${adminField("Closing time","18:00","time")}</div><div class="form-row">${adminField("Venue","De Broodfabriek")}${adminField("City","Rijswijk")}</div>${adminField("Official address","Awaiting final confirmation","text","Validate the production address before publication.")}${adminField("Short description","An international meeting point for health, beauty, wellness and medical tourism.","textarea")}<h2>Ticketing</h2>${adminField("External ticket URL","","url","Required before ticket buttons can be activated.")}<h2>Visitor information</h2>${adminField("Practical information","Doors open at 10:00 on both exhibition days. Review the floor plan and exhibitors before arrival.","textarea")}<h2>Event media</h2><div class="linked-record"><div class="linked-thumb linked-thumb--hero"></div><p><b>Homepage hero</b><span>Temporary approved placeholder · replace with client photo</span></p><button class="admin-btn admin-btn--outline static-save">Change</button></div><div class="linked-record"><div class="linked-thumb linked-thumb--video">▶</div><p><b>Event video</b><span>No approved video connected</span></p><button class="admin-btn admin-btn--outline static-save">Connect</button></div></section><aside><div class="side-card"><h3>Publish settings</h3><div class="toggle-row"><span>Publicly visible</span><button class="switch is-on" type="button"></button></div><div class="toggle-row"><span>Show on homepage</span><button class="switch is-on" type="button"></button></div><div class="toggle-row"><span>Ticket button enabled</span><button class="switch" type="button"></button></div></div><div class="side-card"><h3>Completion</h3><div class="status-item"><span>Dates & times</span><b class="status status--success">Complete</b></div><div class="status-item"><span>Address</span><b class="status status--warning">Review</b></div><div class="status-item"><span>Ticket link</span><b class="status status--danger">Missing</b></div><div class="status-item"><span>Client photography</span><b class="status status--warning">Pending</b></div></div><div class="side-card"><h3>Programme & speakers</h3><p class="helper">3 illustrative speaker profiles are visible in the direction prototype. Replace all names, portraits and topics before publication.</p><a class="admin-btn admin-btn--outline" href="admin.html?page=speakers" style="width:100%;margin-top:12px">Manage speakers →</a></div></aside></div></div>`;
}

function speakersPage() {
  const speakers = [
    ["EK","Dr. Elif Kaya","International patient care","Trust and innovation in international healthcare","Draft"],
    ["SM","Sofia Martins","Beauty innovation","The next generation of responsible beauty","Draft"],
    ["AR","Amira Rahman","Wellness","Wellness without borders","Draft"]
  ];
  return `<div class="admin-page">${pageHead("Speakers & programme", "Manage approved speaker profiles, sessions, visibility and display order.", `<button class="admin-btn admin-btn--outline" type="button">Reorder</button><button class="admin-btn admin-btn--primary static-save" type="button">+ Add speaker</button>`)}
  <div class="prototype-warning"><b>Illustrative content</b><span>Current names, portraits and topics exist only to validate the design. The organiser supplies and approves final speaker information.</span></div>
  <section class="table-panel"><table><thead><tr><th>Speaker</th><th>Sector / role</th><th>Session</th><th>Status</th><th>Actions</th></tr></thead><tbody>${speakers.map(row=>`<tr><td><div class="table-identity"><span class="mini-logo">${row[0]}</span><strong>${row[1]}</strong></div></td><td>${row[2]}</td><td>${row[3]}</td><td><span class="status status--draft">${row[4]}</span></td><td><div class="row-actions"><button class="static-save" aria-label="Edit speaker">✎</button><button class="static-save" aria-label="More speaker actions">•••</button></div></td></tr>`).join("")}</tbody></table></section>
  <div class="admin-grid" style="margin-top:16px"><section class="form-panel"><h2>Speaker profile preview</h2><div class="form-row">${adminField("Full name","Dr. Elif Kaya")}${adminField("Professional role","International patient-care specialist")}</div><div class="form-row">${adminField("Organisation","Client to confirm")}${adminField("Sector","<option>Medical tourism</option><option>Health</option><option>Beauty</option><option>Wellness</option>","select")}</div>${adminField("Approved biography","International patient-care specialist focused on trust, access and cross-border coordination.","textarea")}<h2>Session details</h2><div class="form-row">${adminField("Session date","2026-10-24","date")}${adminField("Start time","11:00","time")}</div>${adminField("Session title","Trust and innovation in international healthcare")}</section><aside><div class="side-card"><h3>Publishing</h3><div class="toggle-row"><span>Profile approved</span><button class="switch" type="button"></button></div><div class="toggle-row"><span>Show on programme</span><button class="switch is-on" type="button"></button></div><div class="toggle-row"><span>Feature on homepage</span><button class="switch is-on" type="button"></button></div>${saveButton}</div></aside></div></div>`;
}

const rows = [
  ["N","Nova Medical Group","Medical tourism","Featured","Published"],
  ["A","Althea Aesthetics","Aesthetic medicine","—","Published"],
  ["L","Lumen Skin Science","Skincare","Featured","Published"],
  ["O","Origin Wellness Lab","Wellness","—","Draft"],
  ["V","Vita Preventive Care","Preventive health","—","Inactive"]
];
function exhibitorsPage() {
  const tableRows = rows.map((row,index)=>`<tr><td><div class="table-identity"><span class="mini-logo">${row[0]}</span><strong>${row[1]}</strong></div></td><td>${row[2]}</td><td>${row[3]}</td><td><span class="status ${row[4]==="Published"?"status--success":row[4]==="Draft"?"status--draft":"status--danger"}">${row[4]}</span></td><td><div class="row-actions"><button class="static-save" aria-label="Edit">✎</button><button class="static-save" aria-label="More">•••</button></div></td></tr>`).join("");
  return `<div class="admin-page">${pageHead("Exhibitors", "Create, edit, reorder, feature, activate and deactivate exhibitor profiles.", `<button class="admin-btn admin-btn--outline" type="button">Reorder</button><button class="admin-btn admin-btn--primary static-save" type="button">+ Add exhibitor</button>`)}<section class="table-panel"><div class="table-tools"><input type="search" placeholder="Search exhibitors…" /><div class="filters"><button class="filter is-active">All</button><button class="filter">Published</button><button class="filter">Draft</button><button class="filter">Inactive</button></div></div><table><thead><tr><th>Exhibitor</th><th>Category</th><th>Homepage</th><th>Status</th><th>Actions</th></tr></thead><tbody>${tableRows}</tbody></table></section></div>`;
}

function mediaPage() {
  const media = [
    ["https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=500&q=80","hero-medical-team.jpg","Homepage hero"],
    ["assets/poster-english.png","campaign-en.png","English campaign"],
    ["assets/poster-turkish.png","campaign-tr.png","Turkish campaign"],
    ["assets/stands-1-2.jpg","stands-1-2.jpg","Stand packages"],
    ["assets/expo-floor-plan.jpg","floor-plan.jpg","Floor plan"],
    ["https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=500&q=80","wellness.jpg","Visitor section"]
  ];
  return `<div class="admin-page">${pageHead("Media library", "Manage approved images, videos, documents and accessibility metadata.", `<button class="admin-btn admin-btn--primary static-save" type="button">Upload media</button>`)}<div class="upload-zone"><div><span>⇧</span><b>Drop approved media here</b><small>Images, approved video references and documents · validation applies</small></div></div><div class="media-grid" style="margin-top:16px">${media.map(item=>`<article class="media-item"><div class="media-thumb" style="background-image:url('${item[0]}')"></div><div class="media-body"><b>${item[1]}</b><small>${item[2]} · Alt text added</small></div></article>`).join("")}</div></div>`;
}

function floorPlanPage() {
  return `<div class="admin-page">${pageHead("Floor plan", "Replace the active static plan and manage the public open/download experience.", `<button class="admin-btn admin-btn--outline" type="button">Preview public page</button><button class="admin-btn admin-btn--primary static-save" type="button">Replace floor plan</button>`)}<div class="admin-grid"><div class="floor-preview"><img src="assets/expo-floor-plan.jpg" alt="Current expo floor plan" /></div><aside><div class="side-card"><h3>Active file</h3><div class="status-item"><span>expo-floor-plan.pdf</span><b class="status status--success">Active</b></div><div class="status-item"><span>Updated</span><b>24 Jul 2026</b></div><div class="status-item"><span>Public download</span><b class="status status--success">Enabled</b></div></div><div class="side-card"><h3>Accessibility</h3>${adminField("Public file name","Health & Beauty Expo floor plan 2026")}${adminField("Alternative text","Static floor plan showing stage, entrance, exhibitor stands and catering areas.","textarea")}${saveButton}</div></aside></div></div>`;
}

function contentPage() {
  return `<div class="admin-page">${pageHead("Page content", "Edit predefined website sections without changing layouts or creating arbitrary pages.", saveButton)}<div class="admin-grid"><section class="form-panel"><h2>Homepage · Hero</h2><div class="form-row">${adminField("Eyebrow","Rijswijk 2026 · International exhibition")}${adminField("Section visibility","<option>Visible</option><option>Hidden</option>","select")}</div>${adminField("Headline","Where health, beauty and opportunity meet.")}${adminField("Supporting text","Connect with world-class healthcare, beauty innovation, holistic wellness and international medical tourism professionals—all under one roof.","textarea")}<div class="form-row">${adminField("Primary button label","Plan your visit")}${adminField("Primary button destination","/tickets")}</div><h2>Homepage · Experience</h2>${adminField("Section title","Discover the ideas shaping better care and better living.")}${adminField("Section description","Health & Beauty Expo brings national and international brands, professionals and visitors together.","textarea")}</section><aside><div class="side-card"><h3>Page sections</h3><div class="toggle-row"><span>Hero</span><button class="switch is-on" type="button"></button></div><div class="toggle-row"><span>Sector bar</span><button class="switch is-on" type="button"></button></div><div class="toggle-row"><span>Experience cards</span><button class="switch is-on" type="button"></button></div><div class="toggle-row"><span>Featured exhibitors</span><button class="switch is-on" type="button"></button></div><div class="toggle-row"><span>Fair Match</span><button class="switch is-on" type="button"></button></div><div class="toggle-row"><span>Paris 2027</span><button class="switch is-on" type="button"></button></div></div><div class="side-card"><h3>Important limitation</h3><p class="helper">This dashboard edits approved fields in existing sections. New layouts and arbitrary sections require development.</p></div></aside></div></div>`;
}

const requestRows = [
  ["Participation","Alara Clinic","Stand 2 / Silver sponsor","New"],
  ["Media","Maya Peters","Digital publication","In review"],
  ["Influencer","Elena V.","Instagram / YouTube","New"],
  ["Contact","Thomas de Boer","Visitor information","Resolved"],
  ["Participation","VitaCare GmbH","Stand 4","In review"]
];
function requestsPage() {
  return `<div class="admin-page">${pageHead("Form requests", "Review contact, participation, media and influencer submissions.", `<button class="admin-btn admin-btn--outline" type="button">Export</button>`)}<div class="admin-grid"><section class="table-panel"><div class="table-tools"><input placeholder="Search requests…" /><div class="filters"><button class="filter is-active">All</button><button class="filter">New</button><button class="filter">In review</button></div></div><table><thead><tr><th>Type</th><th>Name</th><th>Subject</th><th>Status</th></tr></thead><tbody>${requestRows.map((row,index)=>`<tr class="request-row" data-index="${index}"><td><strong>${row[0]}</strong></td><td>${row[1]}</td><td>${row[2]}</td><td><span class="status ${row[3]==="New"?"status--warning":row[3]==="Resolved"?"status--success":"status--draft"}">${row[3]}</span></td></tr>`).join("")}</tbody></table></section><aside class="request-detail" id="requestDetail"><h2>Alara Clinic</h2><p>Participation request · received 12 minutes ago</p><div class="detail-grid"><div class="detail-box"><b>Email</b><span>contact@alara.example</span></div><div class="detail-box"><b>Interest</b><span>Stand 2</span></div><div class="detail-box"><b>Country</b><span>Türkiye</span></div><div class="detail-box"><b>Status</b><span>New</span></div></div><div class="admin-field"><label>Internal note</label><textarea placeholder="Add a note for the team…"></textarea></div><div class="head-actions"><button class="admin-btn admin-btn--outline static-save">Mark in review</button><button class="admin-btn admin-btn--primary static-save">Reply</button></div></aside></div></div>`;
}

function fairMatchPage() {
  const matches = [["FM-017","Nova Medical Group","Sara K.","25 Oct · 11:30","Awaiting"],["FM-016","Althea Aesthetics","Murat D.","24 Oct · 15:00","Proposed"],["FM-015","Vita Preventive Care","Anna R.","24 Oct · 13:30","Confirmed"],["FM-014","Nova Medical Group","Yasin E.","25 Oct · 14:00","Declined"]];
  return `<div class="admin-page">${pageHead("Fair Match", "Manually confirm, propose another time or decline clinic meeting requests.")}<div class="admin-grid"><section class="table-panel"><div class="table-tools"><input placeholder="Search requests…" /><div class="filters"><button class="filter is-active">Open</button><button class="filter">Confirmed</button><button class="filter">Closed</button></div></div><table><thead><tr><th>ID</th><th>Clinic</th><th>Requester</th><th>Preference</th><th>Status</th></tr></thead><tbody>${matches.map(row=>`<tr><td><strong>${row[0]}</strong></td><td>${row[1]}</td><td>${row[2]}</td><td>${row[3]}</td><td><span class="status ${row[4]==="Confirmed"?"status--success":row[4]==="Declined"?"status--danger":"status--warning"}">${row[4]}</span></td></tr>`).join("")}</tbody></table></section><aside class="request-detail"><h2>FM-017 · Sara K.</h2><p>Preferred clinic: Nova Medical Group</p><div class="detail-grid"><div class="detail-box"><b>Date</b><span>25 Oct 2026</span></div><div class="detail-box"><b>Time</b><span>11:30</span></div><div class="detail-box"><b>Email</b><span>sara@example.com</span></div><div class="detail-box"><b>Status</b><span>Awaiting</span></div></div>${adminField("Propose another time","11:45","time")}${adminField("Internal note","","textarea")}<div class="head-actions"><button class="admin-btn admin-btn--outline static-save">Propose</button><button class="admin-btn admin-btn--primary static-save">Confirm</button><button class="admin-btn admin-btn--danger static-save">Decline</button></div></aside></div></div>`;
}

function usersPage() {
  const users=[["AD","Adil Demo","admin@expo.example","Administrator","Active"],["MS","Meryem Staff","staff@expo.example","Employee / Staff","Active"],["OR","Organiser Demo","organiser@expo.example","Organizer","Active"],["LM","Leyla Media","media@expo.example","Employee / Staff","Invited"]];
  return `<div class="admin-page">${pageHead("Users & roles", "Manage internal accounts and server-enforced access levels.", `<button class="admin-btn admin-btn--primary static-save">+ Invite user</button>`)}<section class="table-panel"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>${users.map(user=>`<tr><td><div class="table-identity"><span class="mini-logo">${user[0]}</span><strong>${user[1]}</strong></div></td><td>${user[2]}</td><td>${user[3]}</td><td><span class="status ${user[4]==="Active"?"status--success":"status--warning"}">${user[4]}</span></td><td><div class="row-actions"><button class="static-save">✎</button><button class="static-save">•••</button></div></td></tr>`).join("")}</tbody></table></section><div class="metric-grid" style="margin-top:16px"><article class="metric"><b>Administrator</b><span>Full dashboard, users, event, exhibitors, media, requests and settings.</span></article><article class="metric"><b>Staff</b><span>Allowed daily content, exhibitors, media, requests and event information.</span></article><article class="metric"><b>Organizer</b><span>Limited event and associated exhibitor access only.</span></article><article class="metric"><b>Public</b><span>No administration access. Published content only.</span></article></div></div>`;
}

function languagesPage() {
  const langs=[["NL","Nederlands",92],["TR","Türkçe",86],["EN","English",100],["RU","Русский",68],["AR","العربية · RTL",44]];
  return `<div class="admin-page">${pageHead("Languages", "Review translation completeness and Arabic right-to-left presentation.", `<button class="admin-btn admin-btn--outline">Review missing</button>${saveButton}`)}<div class="translation-grid">${langs.map(lang=>`<article class="language-card"><strong>${lang[0]}</strong><span>${lang[1]}</span><b>${lang[2]}%</b><progress max="100" value="${lang[2]}"></progress><small>${lang[2]===100?"Complete":`${100-lang[2]}% requires review`}</small></article>`).join("")}</div><div class="dash-grid"><section class="panel"><div class="panel-head"><h2>Content review queue</h2><button>Open selected →</button></div><div class="panel-body"><ul class="activity"><li><span>AR</span><p><b>Media accreditation criteria</b><small>Arabic · translation missing</small></p><b class="status status--danger">Missing</b></li><li><span>RU</span><p><b>Participant information</b><small>Russian · requires review</small></p><b class="status status--warning">Review</b></li><li><span>TR</span><p><b>Legal information</b><small>Turkish · client approval required</small></p><b class="status status--warning">Approval</b></li></ul></div></section><section class="side-card"><h3>Arabic RTL checks</h3><div class="status-item"><span>Navigation direction</span><b class="status status--success">Passed</b></div><div class="status-item"><span>Forms</span><b class="status status--success">Passed</b></div><div class="status-item"><span>Mixed numbers / dates</span><b class="status status--warning">Review</b></div><div class="status-item"><span>Floor plan labels</span><b class="status status--draft">Not applicable</b></div></section></div></div>`;
}

function seoPage() {
  return `<div class="admin-page">${pageHead("SEO & accessibility", "Review technical metadata, discoverability and inclusive experience before launch.", `<button class="admin-btn admin-btn--outline">Run preview audit</button>`)}<div class="metric-grid"><article class="metric"><div class="metric-top"><span class="metric-icon">⌕</span><small>Good</small></div><b>13/14</b><span>Pages with metadata</span></article><article class="metric"><div class="metric-top"><span class="metric-icon">▧</span><small>2 missing</small></div><b>96%</b><span>Media with alt text</span></article><article class="metric"><div class="metric-top"><span class="metric-icon">A</span><small>AA target</small></div><b>98%</b><span>Contrast checks</span></article><article class="metric"><div class="metric-top"><span class="metric-icon">↗</span><small>Review</small></div><b>4</b><span>Redirects pending</span></article></div><div class="dash-grid"><section class="panel"><div class="panel-head"><h2>Page checks</h2><button>Export report</button></div><div class="panel-body"><ul class="checklist"><li><span class="check-icon">✓</span><p><b>Heading hierarchy</b><small>One clear H1 and structured H2/H3 sections</small></p><b class="status status--success">Passed</b></li><li><span class="check-icon">✓</span><p><b>Keyboard and focus</b><small>Interactive elements remain reachable and visible</small></p><b class="status status--success">Passed</b></li><li><span class="check-icon pending">!</span><p><b>Event structured data</b><small>Ticket URL required for final record</small></p><b class="status status--warning">Review</b></li><li><span class="check-icon pending">!</span><p><b>Legal metadata</b><small>Awaiting approved legal page copy</small></p><b class="status status--warning">Review</b></li></ul></div></section><section class="side-card"><h3>Indexing</h3><div class="toggle-row"><span>Public site indexing</span><button class="switch is-on"></button></div><div class="toggle-row"><span>Admin indexing</span><button class="switch"></button></div><div class="toggle-row"><span>Sitemap enabled</span><button class="switch is-on"></button></div><div class="toggle-row"><span>Event schema</span><button class="switch is-on"></button></div></section></div></div>`;
}

function settingsPage() {
  return `<div class="admin-page">${pageHead("Settings", "Manage predefined operational values and external connections.", saveButton)}<div class="admin-grid"><section class="form-panel"><h2>General contact</h2><div class="form-row">${adminField("Public email","info@expofuar.nl","email")}${adminField("Public telephone","+31 (0)570 238 100")}</div>${adminField("Official address","Awaiting final confirmation")}<h2>Form routing</h2><div class="form-row">${adminField("General requests recipient","")}${adminField("Participation recipient","")}</div><div class="form-row">${adminField("Media recipient","")}${adminField("Fair Match recipient","")}</div><h2>External links</h2>${adminField("Ticket platform URL","","url","Missing — ticket buttons remain in pending mode.")}<div class="form-row">${adminField("Instagram URL","","url")}${adminField("Facebook URL","","url")}</div></section><aside><div class="side-card"><h3>Environment status</h3><div class="status-item"><span>Database</span><b class="status status--draft">Not connected</b></div><div class="status-item"><span>Authentication</span><b class="status status--draft">Not connected</b></div><div class="status-item"><span>Media storage</span><b class="status status--draft">Not connected</b></div><div class="status-item"><span>Email service</span><b class="status status--draft">Not connected</b></div><p class="helper">Expected for this static validation prototype. Provider setup starts only after design approval.</p></div></aside></div></div>`;
}

function launchPage() {
  const items=[["Public page designs","All approved routes represented","done"],["Responsive layouts","Desktop, tablet and mobile rules","done"],["Five-language shell","NL, TR, EN, RU and Arabic RTL","done"],["Final exhibitor dataset","Client to provide and approve","pending"],["External ticket URL","Client to provide","pending"],["Official address and contacts","Client validation required","pending"],["Legal content","Legal adviser approval required","pending"],["Form recipients","Client to nominate inboxes","pending"],["Production providers","Database, auth, media and email approval","pending"],["Domain and SSL","Scheduled after implementation","pending"]];
  return `<div class="admin-page">${pageHead("Launch checklist", "Track the evidence and approvals needed to move from design validation to production.", `<button class="admin-btn admin-btn--outline">Export checklist</button>`)}<div class="dash-grid"><section class="panel"><div class="panel-head"><h2>Readiness items</h2><span class="status status--warning">6 decisions pending</span></div><div class="panel-body"><ul class="checklist">${items.map(item=>`<li><span class="check-icon ${item[2]==="pending"?"pending":""}">${item[2]==="done"?"✓":"!"}</span><p><b>${item[0]}</b><small>${item[1]}</small></p><b class="status ${item[2]==="done"?"status--success":"status--warning"}">${item[2]==="done"?"Ready":"Pending"}</b></li>`).join("")}</ul></div></section><section><div class="panel"><div class="panel-head"><h2>Overall readiness</h2></div><div class="readiness"><div class="progress-ring"></div><p>Design validation can proceed now.<br />Implementation remains gated.</p></div></div><div class="side-card" style="margin-top:16px"><h3>Next client action</h3><p class="helper">Review public and admin designs, request revisions, then approve the visual direction and page structure before Next.js and Supabase implementation.</p><button class="admin-btn admin-btn--primary static-save" style="width:100%;margin-top:12px">Record design approval</button></div></section></div></div>`;
}

function loginPage() {
  return `<div class="login-preview"><section class="login-art"><p class="kicker">SECURE TEAM ACCESS</p><h1>Manage the expo with clarity.</h1><p>Role-protected access for Administrators, Employees/Staff and Organizers.</p></section><section class="login-form"><form class="login-card preview-form"><img src="assets/health-beauty-expo-logo.png" alt="Health and Beauty Expo" /><h2>Welcome back.</h2><p>Sign in to manage Rijswijk 2026.</p>${adminField("Email address","admin@expo.example","email")}${adminField("Password","demo-password","password")}<button class="admin-btn admin-btn--primary" type="submit">Sign in</button><p class="helper" style="text-align:center">Static access preview — no authentication occurs.</p></form></section></div>`;
}

const renderers={dashboard,event:eventPage,speakers:speakersPage,exhibitors:exhibitorsPage,media:mediaPage,"floor-plan":floorPlanPage,content:contentPage,requests:requestsPage,"fair-match":fairMatchPage,users:usersPage,languages:languagesPage,seo:seoPage,settings:settingsPage,launch:launchPage,login:loginPage};
const rolePermissions = {
  administrator: Object.keys(renderers),
  staff: ["dashboard","event","speakers","exhibitors","media","floor-plan","content","requests","fair-match"],
  organizer: ["dashboard","event","speakers","exhibitors","media"]
};
const roleDescriptions = {
  administrator: "Full prototype access, including users, settings and launch controls.",
  staff: "Day-to-day access to event content, speakers, exhibitors, media and incoming requests.",
  organizer: "Limited preview of event, speaker, associated exhibitor and approved media areas."
};
function showToast(){clearTimeout(toastTimer);toast.classList.add("is-visible");toastTimer=setTimeout(()=>toast.classList.remove("is-visible"),3200)}
function wireAdmin(){document.querySelectorAll(".static-save").forEach(button=>button.addEventListener("click",showToast));document.querySelectorAll(".switch").forEach(button=>button.addEventListener("click",()=>{button.classList.toggle("is-on");showToast()}));document.querySelectorAll(".preview-form").forEach(form=>form.addEventListener("submit",event=>{event.preventDefault();location.href="admin.html?page=dashboard"}));document.querySelectorAll(".filter").forEach(button=>button.addEventListener("click",()=>{button.parentElement.querySelectorAll(".filter").forEach(item=>item.classList.remove("is-active"));button.classList.add("is-active")}))}
function render(){
  const requestedPage=new URLSearchParams(location.search).get("page")||"dashboard";
  const role=rolePreview.value;
  const allowed=rolePermissions[role]||rolePermissions.administrator;
  const page=allowed.includes(requestedPage)?requestedPage:"dashboard";
  adminMain.innerHTML=(renderers[page]||dashboard)();
  adminMain.insertAdjacentHTML("afterbegin",`<div class="role-context"><b>${rolePreview.options[rolePreview.selectedIndex].text} preview</b><span>${roleDescriptions[role]}</span><i>Static permission demonstration</i></div>`);
  document.querySelectorAll("[data-page]").forEach(link=>{
    const permitted=allowed.includes(link.dataset.page);
    link.hidden=!permitted;
    link.classList.toggle("is-active",link.dataset.page===page);
  });
  document.title=`${page.replaceAll("-"," ").replace(/\b\w/g,l=>l.toUpperCase())} — Expo admin preview`;
  wireAdmin();
  window.scrollTo(0,0);
}
sidebarToggle.addEventListener("click",()=>{const open=sidebar.classList.toggle("is-open");sidebarToggle.setAttribute("aria-expanded",String(open))});
rolePreview.value=localStorage.getItem("expo-admin-role")||"administrator";
rolePreview.addEventListener("change",()=>{
  localStorage.setItem("expo-admin-role",rolePreview.value);
  const requestedPage=new URLSearchParams(location.search).get("page")||"dashboard";
  if(!rolePermissions[rolePreview.value].includes(requestedPage)) history.replaceState(null,"","admin.html?page=dashboard");
  render();
});
render();
